fix(service): apply bento project context to runners
bentoml/BentoML pull request #2726
Opened 2022-07-12 12:45 UTC by bojiang

## Description

## Motivation and Context

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the bentoml code style, both `make format` and
  `make lint` script have passed
  ([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)).
- [ ] My change reduces project test coverage and requires unit tests to be added
- [ ] I have added unit tests covering my code change
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-07-12 13:22 UTC, aarnphm reviewed
rmbr to remove the weakref object as well :)

2022-07-13 04:46 UTC, bojiang commented on bentoml/_internal/service/loader.py
> +        on_load_bento(svc, svc.bento)
```suggestion
```

2022-07-13 04:59 UTC, ssheng commented on bentoml/_internal/bento/bento.py
> +
Do we want to raise if another bento has already patched context for model store?

2022-07-13 05:44 UTC, parano requested changes

2022-07-13 05:44 UTC, parano commented on bentoml/_internal/service/service.py
> +
add this to service class:

```python

def __del__(self):
    if self._exit_stack is not None:
        self._exit_stack.close()
```

2022-07-20 02:44 UTC, closed without merging

2022-07-20 02:44 UTC, parano commented
addressed in https://github.com/bentoml/BentoML/pull/2737