feat: added port config for prometheus metrics
bentoml/BentoML pull request #2855
Opened 2022-08-04 02:02 UTC by Proto007

## What does this PR address?

Users can configure a port for prometheus metrics using `config.yml`. Works for both grpc and uvicorn server. For uvicorn server, if the specified port is busy, users can still access the metrics using `/metrics` endpoint.
 
## Before submitting:

- [X] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [X] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [X] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
  those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

## Who can help review?
@aarnphm @ssheng @sauyon  Any feedback is appreciated as always!

2022-08-04 15:20 UTC, Proto007 commented on bentoml/_internal/configuration/default_configuration.yaml
> +    port: 9090
I thought we were using 9090 as default?

2022-08-04 15:22 UTC, Proto007 commented on bentoml/_internal/server/grpc_app.py
> +                        f"Port {self._metrics_port} is already in use. Try using a different port."
`self._metrics_client.start_http_server(self._metrics_port)` does not throw any errors if the port is already in use.

2022-08-04 17:25 UTC, bojiang requested changes
Shall we have another section `grpc` in the comfig?

2022-08-04 17:33 UTC, Proto007 commented
@bojiang I believe we have it already. Are you suggesting we have a separate `metrics_port` section under `grpc`?https://github.com/bentoml/BentoML/blob/258f5ec91c8fa5079dca7c83708d53a3caa3aa45/bentoml/_internal/configuration/default_configuration.yaml#L26-L28

2022-08-04 17:38 UTC, bojiang commented
@Proto007 sounds great. Plus `port` config always come with `host`. So let's add an option for listening host as well?

2022-08-05 15:04 UTC, aarnphm approved these changes
Good job 🥳

2022-08-05 15:05 UTC, merged