EXPERIMENTAL[grpc]: e2e and unit tests
bentoml/BentoML pull request #2984
Opened 2022-09-12 21:57 UTC by aarnphm

## What does this PR address?

This PR is a follow up on #2808 for tests related manners

This includes e2e, unit tests

This will also include a fix in our e2e folder structure where test model should not be
saved under bentoml local model directory if users run tests locally.

2022-09-13 11:51 UTC, pep8speaks commented
Hello @aarnphm, Thanks for updating this PR.



































































* In the file [`tests/unit/grpc/interceptors/test_access_interceptor.py`](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py):

> [Line 4:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing as t' imported but unused
> [Line 6:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'unittest.mock.MagicMock' imported but unused
> [Line 7:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L7): [F401](https://duckduckgo.com/?q=pep8%20F401) 'unittest.mock.PropertyMock' imported but unused
> [Line 9:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L9): [F401](https://duckduckgo.com/?q=pep8%20F401) 'pytest' imported but unused
> [Line 11:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L11): [F401](https://duckduckgo.com/?q=pep8%20F401) 'bentoml.testing.grpc.create_channel' imported but unused
> [Line 12:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L12): [F401](https://duckduckgo.com/?q=pep8%20F401) 'bentoml.testing.grpc.async_client_call' imported but unused
> [Line 13:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L13): [F401](https://duckduckgo.com/?q=pep8%20F401) 'bentoml.testing.grpc.create_bento_servicer' imported but unused
> [Line 14:1](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L14): [F401](https://duckduckgo.com/?q=pep8%20F401) 'bentoml.testing.grpc.make_standalone_server' imported but unused
> [Line 22:5](https://github.com/bentoml/BentoML/blob/2f21b12dd3ef0abe414905175dc22a3405425ee3/tests/unit/grpc/interceptors/test_access_interceptor.py#L22): [F401](https://duckduckgo.com/?q=pep8%20F401) 'bentoml.grpc.interceptors.access.AccessLogServerInterceptor' imported but unused

2022-09-19 20:02 UTC, aarnphm commented
@sauyon I believe this is just flaky CI runner. I couldn't figure out what is wrong.

2022-09-19 22:15 UTC, sauyon commented
I'll take a look.

2022-09-20 03:06 UTC, bojiang requested changes
Please do not use shared conftest

2022-09-20 03:09 UTC, aarnphm commented
I believe it is fine to share conftest.py here. If we want to demonstrate how to write tests for bento, we can do it under the examples folder.

2022-09-20 05:54 UTC, aarnphm commented on bentoml/grpc/utils/__init__.py
> -    )
I forgot to remove these 😃

2022-09-21 02:14 UTC, bojiang commented on bentoml/testing/pytest/plugin.py
> +def reload_directory(
where is this used?

2022-09-21 02:16 UTC, bojiang commented on bentoml/testing/pytest/plugin.py
> +def simple_service() -> bentoml.Service:
It's used by unit test, thus we may just define it in the conftest of unittest

2022-09-21 02:17 UTC, bojiang commented on bentoml/testing/pytest/plugin.py
> +def fixture_propagate_logs() -> t.Generator[None, None, None]:
same as above. let's just define the unit test fixture in the unit test folder?

2022-09-21 02:18 UTC, bojiang requested changes
move unit test utils out `bentoml/testing`

2022-09-29 01:37 UTC, sauyon approved these changes

2022-09-29 01:39 UTC, aarnphm commented on bentoml/grpc/v1alpha1/service.proto
> +    Series series =5;
oh how did it got here :(

2022-09-29 02:07 UTC, aarnphm commented on bentoml/grpc/v1alpha1/service.proto
> +    Series series =5;
I think i address this in one of the PR

2022-09-29 02:34 UTC, bojiang approved these changes

2022-09-29 02:34 UTC, merged