feat: bento description support jinja2 template
bentoml/BentoML pull request #3247
Opened 2022-11-15 16:26 UTC by KimSoungRyoul

## What does this PR address?

feat: #3233

customize bento description support Jinja2 template

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

2022-11-15 16:41 UTC, aarnphm commented on src/bentoml/_internal/bento/bento.py
>      # TODO: add links to documentation that may help with API client development
Can you revert this? The default generated readme should be as it. Should user provide a Jinja template under the docs section, you can then use Template to parse it.

It is also better to create a `Environment` object to parse the jinja template.

2022-11-15 16:41 UTC, aarnphm commented on src/bentoml/_internal/bento/default_svc_readme.py
> +"""
I prefer not to create a separate file for this. We should keep it in line.

2022-11-15 16:43 UTC, aarnphm commented on src/bentoml/_internal/bento/default_svc_readme.py
> +readme_template = """# {{ svc.name }}:{{ svc_version }}
If we are allowing Jinja template like this, we probably want to use block for user to extends or overwrite the template easily.

2022-11-15 16:44 UTC, aarnphm commented on requirements/frameworks-requirements.txt
> +Jinja2>=3.1
This is not necessarily a dependency under frameworks. revert or remove this.

2022-11-15 16:44 UTC, aarnphm requested changes
I left some comments.

2022-11-16 23:52 UTC, aarnphm reviewed
I'm a bit hesitant to add this level of support for Jinja to readme like this.

Jinja is useful if you can pass down variables in Python. For readme specifically, My hunch is you can either just overwrite it with Markdown or provide a readme file.

Can you explain a bit more about the reason for introducing jinja to readme?

2022-11-16 23:52 UTC, aarnphm commented on docs/source/concepts/bento.rst
> +              [![pypi_status](https://img.shields.io/badge/BentoML-{{ bentoml_version }}-informational)](https://pypi.org/project/BentoML)
I wonder if we should include a more descriptive example instead of this.

2022-11-16 23:52 UTC, aarnphm commented on docs/source/concepts/bento.rst
> +   #### I am custom description... blabla
```suggestion
   
   #### Custom heading.
```

2022-11-16 23:52 UTC, aarnphm commented on docs/source/concepts/bento.rst
> +   * Tip: you can also [customize this README](https://docs.bentoml.org/en/latest/concepts/bento.html#description).
probably not useful as an example.

2022-11-16 23:52 UTC, aarnphm commented on docs/source/concepts/bento.rst
> +The description contents support Jinja2 Template, optionally in `Markdown <https://daringfireball.net/projects/markdown/syntax>`_ format. Description
I believe that this is way too complex for it to be in concept page.

Maybe you could create an advanced section for this in `advanced guides`?

2022-11-20 07:49 UTC, KimSoungRyoul commented
> I'm a bit hesitant to add this level of support for Jinja to readme like this.
> 
> Jinja is useful if you can pass down variables in Python. For readme specifically, I think you can either overwrite it with Markdown or provide a readme file.
> 
> Can you explain a bit more about the reason for introducing jinja to readme?

current BentoML can not dynamically obtain bento version information on the custom page and put it in the document.

when I tried to work this feature, I simply worked on using f string to README.md file. (because I want to show only `{svc.name}:{svc_version}` with custom readme )
but it's not universal way. (and it's a temporary solution)  and these will make a bug like a  ...**can not use `{` & `}` to REAEME**


I think you would agree with me that using Jinja for README is too complicated (or over engineering)

but 

BentoML is not personal project. if it was personal project, I didn't hesitate to using f string format.
Jinja is most famous Template engine in python. that's why I used it (it's universal way in python)

Using Jinja,  it's more useful that we advance custom readme

for example we can flexibly by using jinja as follows If we want to improve the more feature to readme  (support yatai to readme)

~~~Jinja
{# pseudo code #}

{% if yatai.url is not None%}

## [go to yatai home]({% yatai.url %})

### these bento's other deployments 
{% for bento in bento_deployment.filter(model_name=~~~) %}
    *  {{ bento.tag['profile'] }} {{ bento.url }}        
{% endfor %}

--> 
go to yatai home(link)

these bento's other deployments 
* dev   https://~~~.svc.~~~:3000  (link)
* stage   https://~~~.svc.~~~:3000 (link)
* prod   https://~~~.svc.~~~:3000 (link)

~~~

#### as a result I think
As there are more requirements to improve the readme(openapi description), I think that Template Engine(jinja) is an indispensable feature in the end.


If you do not want support jinja. how about just support f string to README? or suggest other way to use  `{svc.name}:{svc_version}`  with custom readme
I will modify these pull request
thanks

2022-11-25 08:25 UTC, KimSoungRyoul commented
@aarnphm 
If you are not positive about merging support Jinja, don't hesitate to close this pullrequest :)
but can you make an issue to support feature which can show the model version and bento version in  customizing API Doc 
and suggest an alternative way?

2022-12-05 09:41 UTC, KimSoungRyoul commented
> @aarnphm If you are not positive about merging support Jinja, don't hesitate to close this pullrequest :) but can you make an issue to support feature which can show the model version and bento version in customizing API Doc and suggest an alternative way?

i'm still waiting  😢

2023-01-15 08:23 UTC, KimSoungRyoul commented
@aarnphm 
hi I want to specify and manage not only the version of the API server through API Docs (README), but also the version of the model that is deployed as a runner.
If this PR (`support Jinja Template to the README.md file`) is deemed unnecessary for your team, could you tell me how your team can support the above-mentioned feature?
I am willing to implement this and re-upload the PR.

thanks

2023-01-16 10:56 UTC, closed without merging