tools: Ruff
bentoml/BentoML pull request #3539
Opened 2023-02-08 16:11 UTC by aarnphm

Ruff is the new linter that is 50x faster than pylint, implements most rules from pylint and flake8 and others linter.

It is a lot faster 😄

2023-02-08 18:56 UTC, jjmachan commented
+1 to this! Heard a lot of people rave about how fast it is, let me try it out locally

2023-02-08 21:03 UTC, sauyon reviewed
Who knew rust was faster than python ;)

2023-02-08 21:20 UTC, aarnphm commented on pyproject.toml
> +ignore = ["E501", "E741", "W605"]
E501: Line too long
E741: Do not use I, O and l because it is deemed to be confusing
W605: invalid escape sequence for regex.

2023-02-08 21:20 UTC, aarnphm commented on pyproject.toml
> +"__init__.py" = ["E402"]
yes

2023-02-08 21:21 UTC, aarnphm commented on .github/workflows/ci.yml
> +        run: ruff check src tests examples --fix
no reason. Let me remove it.

2023-02-08 21:22 UTC, aarnphm commented on Makefile
> +	@ruff check src examples tests --fix
I think we should run `--fix` with black and isort.

2023-02-08 21:23 UTC, aarnphm commented on pyproject.toml
> +ignore = ["E501", "E741", "W605"]
tip: you can find out the rule description with ```bash
ruff rule <RULE>
```

2023-02-08 22:39 UTC, sauyon commented on pyproject.toml
> +ignore = ["E501", "E741", "W605"]
Sure, but I meant in the file here.

2023-02-08 22:41 UTC, sauyon commented on Makefile
> +	@ruff check src examples tests --fix
I think I would assume that `lint` doesn't touch my files; maybe we should move this to `format`?

2023-02-08 22:42 UTC, sauyon commented on pyproject.toml
> +"__init__.py" = ["E402"]
Then we should only exclude that file in particular, I think.

2023-02-08 22:46 UTC, aarnphm commented on pyproject.toml
> +"__init__.py" = ["E402"]
done.

2023-02-08 22:46 UTC, aarnphm commented on Makefile
> +	@ruff check src examples tests --fix
also done.

2023-02-09 03:43 UTC, sauyon requested changes

2023-02-09 03:43 UTC, sauyon commented on pyproject.toml
> +# tip: use 'ruff rule <RULE>' to see the description of a rule
```suggestion
# We ignore E501 (line too long) here because we keep user-visible strings on one line.
```

2023-02-09 04:21 UTC, sauyon approved these changes

2023-02-09 05:12 UTC, merged