docs: add quick exceptions docs
bentoml/BentoML pull request #3609
Opened 2023-02-23 05:32 UTC by aarnphm

Add a quick reference to our exceptions.

Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

2023-02-23 07:33 UTC, sauyon requested changes

2023-02-23 07:33 UTC, sauyon commented on src/bentoml/exceptions.py
> +    Raise when the state of an object is not valid.
Maybe we should reword all of these from "Raise" to "Raised"?

2023-02-23 07:33 UTC, sauyon commented on src/bentoml/exceptions.py
> +    Some BentoML components has optional dependencies that can be installed as extensions.
```suggestion
    Some BentoML components have optional dependencies that can be installed as extensions.
```

2023-02-23 07:33 UTC, sauyon commented on src/bentoml/exceptions.py
> +    will still works without ``pydantic`` installed.
```suggestion
    will still work without ``pydantic`` installed.
```

2023-02-23 07:33 UTC, sauyon commented on src/bentoml/exceptions.py
>  class ImportServiceError(BentoMLException):
"failed to import the user's service file" probably is more accurate than "service.py".

2023-02-23 07:33 UTC, sauyon commented on src/bentoml/exceptions.py
> +    """Raise when there is an error during push/pull bentos/models."""
Maybe something like "when communicating with the Bento Cloud server"?

2023-03-02 02:38 UTC, sauyon commented on src/bentoml/exceptions.py
> +    """Raised when failed to import the user's service file."""
```suggestion
    """Raised when BentoML failed to import the user's service file."""
```

2023-03-02 02:39 UTC, sauyon approved these changes
Last thing I think.

2023-03-02 06:01 UTC, aarnphm commented
@sauyon PTAL.

2023-03-02 06:07 UTC, sauyon approved these changes

2023-03-02 06:11 UTC, merged