chore: http client healthcheck
bentoml/BentoML pull request #3636
Opened 2023-03-04 16:04 UTC by denyszhak

## What does this PR address?

Fixes #3315 

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

2023-03-04 20:20 UTC, aarnphm reviewed
LGTM. Would kindly request if you can write a quick test for this.

You can write the test under any of the `test/e2e/bento_[grpc|http]_server`.

2023-03-07 22:11 UTC, denyszhak commented
> LGTM. Would kindly request if you can write a quick test for this.
> 
> You can write the test under any of the `test/e2e/bento_[grpc|http]_server`.

wdyt if I move simple_service feature on the level above unit and e2e tests? or do you want me to create a separate Service instance for client test

2023-03-07 23:19 UTC, aarnphm commented
Lets keep the simple_service fixture in unit, and you can write a simple client test under e2e instead.

No need to create a separate Service instance. The e2e service test will setup everything.

2023-03-07 23:54 UTC, denyszhak commented
> Lets keep the simple_service fixture in unit, and you can write a simple client test under e2e instead.
> 
> No need to create a separate Service instance. The e2e service test will setup everything.

Thanks, that makes sense, didn't know the load() API, please check

2023-03-08 04:31 UTC, aarnphm requested changes
Some finals comments. Otherwise LGTM

2023-03-08 04:31 UTC, aarnphm commented on tests/e2e/bento_server_http/tests/test_client.py
> +pytestmark = pytest.mark.asyncio
Lets not do this
```suggestion
```

2023-03-08 04:31 UTC, aarnphm commented on tests/e2e/bento_server_http/tests/test_client.py
> +    resp = await http_client.async_health()
```suggestion
@pytest.mark.asyncio
async def test_async_health(http_client: HTTPClient) -> None:
    resp = await http_client.async_health()
```

2023-03-08 08:37 UTC, denyszhak commented on tests/e2e/bento_server_http/tests/test_client.py
> +pytestmark = pytest.mark.asyncio
Of curiosity, what's the reason?

2023-03-08 10:54 UTC, aarnphm approved these changes
Thanks for the contribution.

2023-03-08 10:54 UTC, merged