chore(dispatcher): use slots class instead of a tuple
bentoml/BentoML pull request #3731
Opened 2023-03-29 15:59 UTC by sauyon

Makes jobs slightly easier to read.

2023-03-29 16:22 UTC, sauyon commented
This one has been validated only with a quick server and ~50 requests.

2023-03-30 05:43 UTC, bojiang requested changes
This is on the critical path. We shall keep everything lightweight. AFAIK creating tuples is much faster than objects, maybe we should do some benchmark for the attr slots.

2023-03-31 03:32 UTC, aarnphm commented
I believe #3664 depends on this PR. What is the decision on this @bojiang @sauyon ?

2023-04-04 03:43 UTC, bojiang approved these changes

2023-04-04 05:47 UTC, aarnphm approved these changes

2023-04-04 05:48 UTC, merged