docs: Update the adaptive batching doc
bentoml/BentoML pull request #4571
Opened 2024-03-12 09:01 UTC by Sherlock113

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [x] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

2024-03-12 09:02 UTC, frostming commented on docs/source/guides/adaptive-batching.rst
> +        # Use a np.ndarray to encapsulate multiple text inputs in one batch
Missing `@bentoml.api` decorator

2024-03-12 11:16 UTC, frostming requested changes
Hi, I would like suggest adding a more complex batching example.

Since BentoML only supports one argument for batchable API, in some cases users want to pass multiple arguments, this can be workarounded with a composite input type and a wrapper service:

```python
from __future__ import annotations

from pathlib import Path

import bentoml
from pydantic import BaseModel


class BatchInput(BaseModel):
    image: Path
    threshold: float


@bentoml.service
class ImageService:
    @bentoml.api(batchable=True)
    def predict(self, inputs: list[BatchInput]) -> list[Path]:
        # inference logic here using the image and threshold
        return [input.image for input in inputs]


@bentoml.service
class MyService:
    batch = bentoml.depends(ImageService)

    @bentoml.api
    def generate(self, image: Path, threshold: float) -> Path:
        result = self.batch.predict([BatchInput(image=image, threshold=threshold)])
        return result[0]
```

2024-03-13 01:57 UTC, Sherlock113 commented
@frostming Thanks for the explanation. This use case is very helpful and I added another section to explain it. Please take a look.

2024-03-13 02:09 UTC, frostming approved these changes

2024-03-13 02:11 UTC, merged