feat(monitoring): don't set environment variables and allow use of GRPC `OTLPLogExporter`
bentoml/BentoML pull request #4807
Opened 2024-06-14 13:39 UTC by judahrand

## What does this PR address?

Fixes #(issue)

## Before submitting:

- [ ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ ] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
- [ ] Did your changes require updates to the documentation? Have you updated
      those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
- [ ] Did you write tests to cover your changes?

2024-06-15 13:40 UTC, aarnphm requested changes
no, we need to set via environment for controlling on kubernetes.

I'm find with having hierarchical to check for env -> variable

gPRC exporter seems to be a separate PR.

2024-06-15 14:13 UTC, judahrand commented
> no, we need to set via environment for controlling on kubernetes.

Why? Is that specific to BentoCloud because the user doesn't actually have control over the Pod's spec? Otherwise, the user should still be responsible for setting their environment variables of their own Pods?

> I'm find with having hierarchical to check for env -> variable

That still strikes me as leading so some slightly odd behaviour. For example, imagine you want to send traces and logs to two different OTLP Collectors (as I do). I set the environment variables match the endpoint I want to send the traces to and I configure the logs via code on in the `bentoml.service` decorator. Where do my traces go? 🤷‍♂️ I genuinely don't know the answer but it seems very confusing and delicate and could change unexpectedly given that the code is sometimes manually overriding my environment variables but sometimes not.

2024-06-15 14:14 UTC, judahrand commented
> gPRC exporter seems to be a separate PR.

True... but also some of the arguments and environment variables being set literally do nothing 😆 `insecure` for example seems to only be relevant for the GRPC exporter. Happy to split it out but surprised it made it through code review.

2024-06-15 14:25 UTC, judahrand commented
> no, we need to set via environment for controlling on kubernetes.

Alternatively, should we be setting only the `OTEL_EXPORTER_OTLP_LOGS_ENDPOINT` variable for the endpoint? Still not sure setting these at all is great. But it'd be better.

2025-01-18 20:44 UTC, aarnphm commented
we can revisit this if you have bandwidth

2025-03-27 02:11 UTC, closed without merging